"use client";

import React, { Suspense } from "react";
import { AuthProvider } from "@contexts/AuthContext"; // Archivo para manejar el contexto de autenticación
import { RefineContext } from "./_refine_context";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Refine App</title>
        <meta name="description" content="Generated by create refine app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Suspense fallback={<div>Cargando...</div>}>
          <AuthProvider>
            <RefineContext>{children}</RefineContext>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
